### ISSUE TITLE
X90r4-366TB or 622TB always adds NVME-QLC vs leaving it NVME in the chassis (366 or 366-256)

### ISSUE THREAD

**Issue by barman2k** [sile16/purerackdiagram#7]
I only tried X90r4 but once you add 20 DFMs in the chassis is ASSUMES you want QLC vs TLC.

**Comment by sile16** [comment]
Yes, that does look incorrect.  As a quick work around you can do 183/183 instead of 366.  I will have to look and see how to resolve the conflict in sizes.  Thank you for letting me know!

**Comment by sile16** [comment]
the most recent commit fixes this issue.

**Comment by sile16** [comment]
Please note that the new 36.6 TLC modules overlap the 366 size.  So 366 is 10 modules use 183/183 to use 18.3 modules.
