### ISSUE TITLE
about fa-c40r3 back view

### ISSUE THREAD

**Issue by ryuyamag** [sile16/purerackdiagram#8]
hello team,
I am facing the following issue. If there is any workaround or advice you could provide, I would appreciate it.

I'm trying to create a back view of fa-c40r3.
I would like to create a diagram without mezz card, but emez is automatically configured and cannot be emptied.

**Comment by sile16** [comment]
this has been fixed, the c40r3 indeed does not include a mezz by default, so that has been fixed, also by passing mezz=none you can also override the default selection and not populate a mezz card.
