### ISSUE TITLE
Default C50R4 ETH image update

### ISSUE THREAD

**Issue by yelkcubj** [sile16/purerackdiagram#9]
Please update the default C50R4-ETH image.  It has 2 x dual port 10/25Gb adapters in Slots 1 & 3.  The current default image in the builder only has one in slot 1.  Custom image to match the default. https://github.com/sile16/purerackdiagram/assets/42850769/1c8a99cf-41b1-4993-804c-5e0e26a0cb50

**Comment by sile16** [comment]
Thank you, for bringing up this issue.  The default config has been corrected.
